testcases:
- interfaceName: /steam-featured/homeConfig/removeIndexConfig
  case:
  - testPoint: 删除一个运营位配置
    preConditions:
    - preInterfaceAddOneOperpsn
    operationSteps: testOperpsnAlertNor
    testData:
    - title: 让MakeX成为青少年释放自我的舞台-接口自动化-勿动
      picPath: http://uat-steam.opg.cn/_static/admin/images/resource/20180425112224_258421.jpg
      position: '03'
      oldListOrder: 1
      listOrder: 1
      displayType: '1'
      itemId: 121
      resourceId: 1696
      id: 52
      caseid: operpsn_del_1
      testPoint: 删除一个运营位配置
    expectedResult:
      code: '000000'
