testcases:
- interfaceName: /steam-featured/homeConfig/listData
  case:
  - testPoint: 查询运营位配置
    preConditions:
    - ''
    operationSteps: testOperpsnQueryNor
    testData:
    - position: '03'
      title: 让MakeX成为青少年释放自我的舞台-接口自动化-勿动
      caseid: operpsn_query_1
      testPoint: 查询运营位配置
    expectedResult:
      code: '000000'
